# @import ./auth.http

###
# @ref auth
GET http://localhost:5000/api/words?name=создать
Authorization: Bearer {{ auth.accessToken }}

###
# @ref auth
GET http://localhost:5000/api/words?name=задАть
Authorization: Bearer {{ auth.accessToken }}
